/* Text to put at the beginning of the generated file. Probably a license. */

#ifndef CARBON_H
#define CARBON_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace carbon {
#endif // __cplusplus

typedef struct HostIterator HostIterator;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

HostIterator *create_host_iter(void);

void free_host(char *hostname_ptr);

void free_host_iter(HostIterator *iter_ptr);

char *next_host(HostIterator *iter_ptr);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#ifdef __cplusplus
} // namespace carbon
#endif // __cplusplus

#endif /* CARBON_H */
